#!/usr/bin/env groovy

def builders = [:]

node('linux') {
  checkout scm

  workloads = sh(script: "find . -type f -name 'workload-test.groovy'", returnStdout: true).trim().split('\n');
  workloads.each {
      def workload = load it
      builders[it] = {
          workload.execute()
      }
  }
}

parallel builders
