
@Library('sec_ci_libs@v2-latest') _

def master_branches = ["master", ] as String[]

pipeline {
  agent none


  stages {
    stage("Verify author for PR") {
      agent {
        label "py36"
      }
      when {
        beforeAgent true
        changeRequest()
      }
      steps {
        user_is_authorized(master_branches, '8b793652-f26a-422f-a9ba-0d1e47eb9d89', '#sre')
      }
    }

    stage('Build') {
      parallel {
          stage('Build DC/OS') {
	    agent {
	       label 'ec2-large-20200213'
	    }
            steps {
              ansiColor('xterm') {
	        sh '''
                  until docker info >/dev/null 2>&1; do
                    if sudo systemctl is-active docker >/dev/null; then
                      sudo systemctl start docker
                      continue
                    fi
		    systemctl status docker
                    echo "Docker running but not yet responding. Sleeping 10s..."
                    sleep 10
                  done
                  echo "Docker is running"
		'''
	        sh './build_local.sh'
	      }
	    }
	  }
          stage('Tox') {
	    agent {
	       // TODO(kjeschkies): Use small or medium: Use small or mediumm
	       label 'ec2-large-20200213'
	    }
            steps {
              ansiColor('xterm') {
	        sh 'pip install tox'
	        sh 'tox'
	      }
	    }
	  }
      }
    }
  }
}
